
server:
  port: !!str 8080
  readtimeout: 5
  writetimeout: 5
  idletimeout: 5
postgres:
  dbdriver: postgres 
  host: postgresdb
  port: 5432
  username: postgres
  password: admin
  schema: postgres
  sslmode: disable
  migrationpath: "file://internal/migrations"

