
server:
  port: !!str 8080
  host: localhost
  readtimeout: 5
  writetimeout: 5
  idletimeout: 5
postgres:
  dbdriver: postgres 
  host: localhost
  port: 5432
  username: postgres
  password: Wild54323
  schema: postgres
  sslmode: disable
  migrationpath: "file://C:/Develop/testtasks/wallet/internal/migrations"
